name: groceries_app
description: A demo application for Widgetbook and how to implement a design system from Figma.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  assets:
    path: assets
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.7.0
  go_router: ^12.1.0
  google_fonts: ^6.2.0
  intl: ^0.20.2

dev_dependencies:
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
